import { CharacterProfile, Question } from "@/lib/types";

export const questions: Question[] = [
  {
    id: "q1",
    axis: "attachment",
    prompt: "연락이 늦어지면?",
    options: [
      { id: "q1a", label: "별로 신경 안 쓴다", score: { attachment: { wolf: 2 } } },
      { id: "q1b", label: "계속 신경 쓰이고 불안하다", score: { attachment: { spark: 2 } } },
      { id: "q1c", label: "상황에 따라 다르다", score: { attachment: { lion: 2 } } },
    ],
  },
  {
    id: "q2",
    axis: "attachment",
    prompt: "누군가와 가까워지면?",
    options: [
      { id: "q2a", label: "부담돼서 거리를 두게 된다", score: { attachment: { wolf: 2 } } },
      { id: "q2b", label: "더 가까워지고 싶어진다", score: { attachment: { spark: 2 } } },
      { id: "q2c", label: "자연스럽게 유지한다", score: { attachment: { lion: 2 } } },
    ],
  },
  {
    id: "q3",
    axis: "attachment",
    prompt: "갈등 상황이 생기면?",
    options: [
      { id: "q3a", label: "피하거나 시간을 둔다", score: { attachment: { wolf: 2 } } },
      { id: "q3b", label: "바로 해결하려고 집착한다", score: { attachment: { spark: 2 } } },
      { id: "q3c", label: "대화로 풀려고 한다", score: { attachment: { lion: 2 } } },
    ],
  },
  {
    id: "q4",
    axis: "dopamine",
    prompt: "심심할 때 나는?",
    options: [
      { id: "q4a", label: "더 자극적인 걸 찾는다", score: { dopamine: { hunter: 2 } } },
      { id: "q4b", label: "그냥 계속 폰을 본다", score: { dopamine: { scroller: 2 } } },
      { id: "q4c", label: "할 일을 찾는다", score: { dopamine: { goal: 2 } } },
    ],
  },
  {
    id: "q5",
    axis: "dopamine",
    prompt: "콘텐츠를 볼 때 나는?",
    options: [
      { id: "q5a", label: "자극적인 걸 선호한다", score: { dopamine: { hunter: 2 } } },
      { id: "q5b", label: "끊지 못하고 계속 본다", score: { dopamine: { scroller: 2 } } },
      { id: "q5c", label: "필요한 것만 본다", score: { dopamine: { goal: 2 } } },
    ],
  },
  {
    id: "q6",
    axis: "dopamine",
    prompt: "목표가 없을 때 나는?",
    options: [
      { id: "q6a", label: "재미있는 것만 찾는다", score: { dopamine: { hunter: 2 } } },
      { id: "q6b", label: "시간만 계속 보낸다", score: { dopamine: { scroller: 2 } } },
      { id: "q6c", label: "새로운 목표를 만든다", score: { dopamine: { goal: 2 } } },
    ],
  },
  {
    id: "q7",
    axis: "bias",
    prompt: "실패했을 때 나는?",
    options: [
      { id: "q7a", label: "더 잃지 않으려 조심한다", score: { bias: { loss: 2 } } },
      { id: "q7b", label: "내 판단이 맞았다고 생각한다", score: { bias: { belief: 2 } } },
      { id: "q7c", label: "운이 안 좋았다고 생각한다", score: { bias: { luck: 2 } } },
    ],
  },
  {
    id: "q8",
    axis: "bias",
    prompt: "중요한 선택을 할 때 나는?",
    options: [
      { id: "q8a", label: "손해 안 보는 쪽을 고른다", score: { bias: { loss: 2 } } },
      { id: "q8b", label: "내 확신을 따른다", score: { bias: { belief: 2 } } },
      { id: "q8c", label: "감이나 흐름을 따른다", score: { bias: { luck: 2 } } },
    ],
  },
  {
    id: "q9",
    axis: "bias",
    prompt: "내가 틀렸을 때 나는?",
    options: [
      { id: "q9a", label: "다시는 실수 안 하려고 한다", score: { bias: { loss: 2 } } },
      { id: "q9b", label: "그래도 내 생각을 유지한다", score: { bias: { belief: 2 } } },
      { id: "q9c", label: "다시 시도해본다", score: { bias: { luck: 2 } } },
    ],
  },
  {
    id: "q10",
    axis: "selfWorth",
    prompt: "남의 시선을 나는?",
    options: [
      { id: "q10a", label: "많이 신경 쓴다", score: { selfWorth: { mask: 2 } } },
      { id: "q10b", label: "신경 안 쓰는 척한다", score: { selfWorth: { wall: 2 } } },
      { id: "q10c", label: "크게 신경 안 쓴다", score: { selfWorth: { rooted: 2 } } },
    ],
  },
  {
    id: "q11",
    axis: "selfWorth",
    prompt: "실패를 하면 나는?",
    options: [
      { id: "q11a", label: "숨기고 싶어진다", score: { selfWorth: { mask: 2 } } },
      { id: "q11b", label: "이유를 찾거나 방어한다", score: { selfWorth: { wall: 2 } } },
      { id: "q11c", label: "인정하고 받아들인다", score: { selfWorth: { rooted: 2 } } },
    ],
  },
  {
    id: "q12",
    axis: "selfWorth",
    prompt: "스스로를 평가할 때 나는?",
    options: [
      { id: "q12a", label: "남들과 비교한다", score: { selfWorth: { mask: 2 } } },
      { id: "q12b", label: "약점을 숨기려 한다", score: { selfWorth: { wall: 2 } } },
      { id: "q12c", label: "있는 그대로 본다", score: { selfWorth: { rooted: 2 } } },
    ],
  },
  {
    id: "q13",
    axis: "decision",
    prompt: "결정을 내릴 때 나는?",
    options: [
      { id: "q13a", label: "빠르게 결정한다", score: { decision: { flash: 2 } } },
      { id: "q13b", label: "계속 미루게 된다", score: { decision: { delay: 2 } } },
      { id: "q13c", label: "충분히 고민 후 결정한다", score: { decision: { strategist: 2 } } },
    ],
  },
  {
    id: "q14",
    axis: "decision",
    prompt: "결정 후 나는?",
    options: [
      { id: "q14a", label: "후회를 자주 한다", score: { decision: { flash: 2 } } },
      { id: "q14b", label: "잘한 건지 계속 고민한다", score: { decision: { delay: 2 } } },
      { id: "q14c", label: "크게 신경 쓰지 않는다", score: { decision: { strategist: 2 } } },
    ],
  },
  {
    id: "q15",
    axis: "decision",
    prompt: "중요한 선택이 있을 때 나는?",
    options: [
      { id: "q15a", label: "바로 선택한다", score: { decision: { flash: 2 } } },
      { id: "q15b", label: "최대한 미룬다", score: { decision: { delay: 2 } } },
      { id: "q15c", label: "정보 모아서 결정한다", score: { decision: { strategist: 2 } } },
    ],
  },
];

export const attachmentProfiles: Record<string, CharacterProfile> = {
  wolf: {
    id: "wolf",
    emoji: "🐺",
    imagePath: "/assets/wolf.png",
    name: "거리두는 늑대",
    hook: "가까워지고 싶지만 가까워지는 순간 도망칩니다",
    summary: "혼자가 편한 척하지만, 막상 깊은 연결은 계속 갈망하는 타입입니다.",
    aura: "차갑고 무심해 보이지만 속으로는 계속 계산하는 회피형",
    accent: "wolf",
    keywords: ["회피", "거리감", "통제"],
    detail: [
      "다가오는 사람을 밀어내고 나서야 외로움을 느끼기 쉽습니다.",
      "상대를 싫어해서가 아니라, 휘말리는 감각이 두려워 선을 긋습니다.",
      "표현을 미룰수록 오해는 커지고 관계는 서서히 식습니다.",
    ],
    pattern: "초반에는 매력적이지만 관계가 진지해질수록 답장이 느려지고 감정을 감춥니다.",
    trigger: "상대가 관계를 정의하거나 더 자주 연결되길 바라는 순간 숨이 막히기 시작합니다.",
    weakness: "상처받지 않으려 만든 거리감이 결국 진짜 원하는 친밀감까지 같이 밀어냅니다.",
    advice: "도망가기 전에 '지금 조금 부담스럽다'고 말하는 것만으로도 관계 파괴를 크게 줄일 수 있습니다.",
  },
  spark: {
    id: "spark",
    emoji: "🐶",
    imagePath: "/assets/spark.png",
    name: "매달리는 불꽃",
    hook: "사랑을 원하지만 확인받지 못하면 불안해집니다",
    summary: "애정이 깊을수록 마음보다 불안이 먼저 달려나가는 타입입니다.",
    aura: "따뜻하고 직진이지만 불안이 켜지면 관계를 태워버리는 집착형",
    accent: "spark",
    keywords: ["불안", "확인욕구", "집착"],
    detail: [
      "연락 간격과 말투 변화에 감정이 크게 흔들리는 편입니다.",
      "확인을 요구할수록 안심되기보다 더 목이 마를 수 있습니다.",
      "좋아하는 마음이 커질수록 상대를 더 몰아붙일 위험이 있습니다.",
    ],
    pattern: "좋아할수록 더 표현하고 더 묻고 더 확인하려는 움직임이 강해집니다.",
    trigger: "읽씹, 짧아진 답장, 애매한 태도처럼 확신을 주지 않는 장면에 특히 약합니다.",
    weakness: "버려질까 봐 붙잡지만 그 불안한 행동이 오히려 상대를 멀어지게 만들 수 있습니다.",
    advice: "'왜 그래?'보다 '지금 사실 좀 불안해'라고 말하면 집착보다 훨씬 건강하게 전달됩니다.",
  },
  lion: {
    id: "lion",
    emoji: "🦁",
    imagePath: "/assets/lion.png",
    name: "균형 잡힌 사자",
    hook: "가까워질 줄 알고 물러날 줄도 압니다",
    summary: "관계에서 감정과 거리감을 비교적 건강하게 조절하는 타입입니다.",
    aura: "단단하고 침착해서 주변까지 안정시키는 중심형",
    accent: "lion",
    keywords: ["안정", "배려", "중심감"],
    detail: [
      "갈등이 생겨도 감정과 상황을 분리해서 보려는 힘이 있습니다.",
      "가까워져도 자신을 잃지 않고, 멀어져도 과하게 무너지지 않습니다.",
      "다만 늘 괜찮은 역할을 하다 본인 감정을 뒤로 미룰 수 있습니다.",
    ],
    pattern: "관계의 속도를 무리하게 끌어당기지도 밀어내지도 않고 균형을 맞춥니다.",
    trigger: "밀당이 반복되거나 감정을 계속 추측하게 하는 상황에서 피로가 누적됩니다.",
    weakness: "안정적이지만 너무 이해하는 쪽에 서면 자기 욕구가 흐려질 수 있습니다.",
    advice: "상대를 배려하는 만큼 나의 기준과 원하는 바도 분명히 말해야 균형이 유지됩니다.",
  },
};

export const dopamineProfiles: Record<string, CharacterProfile> = {
  hunter: {
    id: "hunter",
    emoji: "🔥",
    imagePath: "/assets/hunter.png",
    name: "자극 사냥꾼",
    hook: "평범함을 못 견디고 항상 더 강한 자극을 찾습니다",
    summary: "쉽게 질리고 쉽게 빠지며, 늘 더 센 것을 원하는 타입입니다.",
    aura: "강한 쾌감과 즉각 반응에 몸이 먼저 반응하는 질주형",
    accent: "hunter",
    keywords: ["짜릿함", "충동", "질주"],
    detail: [
      "익숙해지는 순간 흥미가 빠르게 식는 편입니다.",
      "콘텐츠, 관계, 취미 모두 강도 높은 경험에 끌립니다.",
      "짧은 만족 뒤 더 큰 공허가 따라오기 쉽습니다.",
    ],
    pattern: "재미가 약해지는 순간 바로 다음 자극을 찾고 기준은 점점 높아집니다.",
    trigger: "반복, 루틴, 예측 가능한 하루가 길어질수록 자극 탐색 모드가 켜집니다.",
    weakness: "평범한 일상을 못 버티면 결국 삶 전체가 쉽게 지루해지고 불안정해집니다.",
    advice: "강한 자극을 끊기보다 운동, 창작, 도전처럼 에너지를 태우는 쪽으로 옮기면 오래 갑니다.",
  },
  scroller: {
    id: "scroller",
    emoji: "🌀",
    imagePath: "/assets/scroller.png",
    name: "무한 스크롤러",
    hook: "멈추지 못합니다. 재미가 아니라 습관으로 계속하게 됩니다",
    summary: "강한 자극보다 끊기지 않는 잔자극에 묶여 있는 타입입니다.",
    aura: "멈추는 것보다 계속 흘려보내는 게 편한 무의식 몰입형",
    accent: "scroller",
    keywords: ["공허회피", "습관", "잔자극"],
    detail: [
      "정말 보고 싶어서라기보다 멈추기 어려워서 계속 보는 경우가 많습니다.",
      "시간은 썼는데 기억나는 건 거의 없는 날이 반복될 수 있습니다.",
      "핵심은 쾌락보다 공백 회피일 가능성이 큽니다.",
    ],
    pattern: "딱히 원하는 게 없어도 손이 먼저 움직이고, 어느새 시간이 사라집니다.",
    trigger: "피곤한 밤, 애매한 공백, 감정을 마주하기 싫은 순간에 특히 길어집니다.",
    weakness: "세게 망가지진 않아도 에너지와 집중력이 하루 종일 새어나가게 됩니다.",
    advice: "완전히 끊으려 하지 말고 가장 많이 무너지는 시간대 하나부터 막는 게 현실적입니다.",
  },
  goal: {
    id: "goal",
    emoji: "🎯",
    imagePath: "/assets/goal.png",
    name: "목표 집착형",
    hook: "목표가 생기면 몰입하지만 없으면 아무것도 하지 않습니다",
    summary: "도파민을 놀이보다 성취에서 강하게 끌어오는 타입입니다.",
    aura: "성과와 진전에 중독되기 쉬운 고성능 집착형",
    accent: "goal",
    keywords: ["성과", "통제", "번아웃"],
    detail: [
      "해야 할 걸 끝내야 비로소 안심이 되는 편입니다.",
      "목표가 선명할수록 몰입력은 강력하지만, 없으면 급격히 무기력해질 수 있습니다.",
      "성장 욕구가 번아웃으로 뒤집히는 순간이 숨어 있을 수 있습니다.",
    ],
    pattern: "쉬는 시간에도 다음 계획을 떠올리고, 성과가 없으면 하루를 날린 듯 느낍니다.",
    trigger: "비교, 지연, 생산성 저하를 감지하는 순간 집착과 자책이 동시에 올라옵니다.",
    weakness: "목표가 삶의 전부가 되면 쉬는 법을 잃고 효율도 감정도 한 번에 무너질 수 있습니다.",
    advice: "성과 없는 휴식을 실패로 보지 않는 훈련이 필요합니다. 그래야 오래 갑니다.",
  },
};

export const biasProfiles: Record<string, CharacterProfile> = {
  loss: {
    id: "loss",
    emoji: "💸",
    imagePath: "/assets/loss.png",
    name: "손실 공포가",
    hook: "잃는 것을 극도로 싫어해서 기회를 놓칩니다",
    summary: "이득보다 손해 가능성에 더 크게 반응하는 타입입니다.",
    aura: "실수와 손해를 피하려는 감각이 유난히 예민한 보수형",
    accent: "loss",
    keywords: ["회피", "안전", "손해공포"],
    detail: [
      "좋은 기회가 와도 잃을 가능성부터 먼저 계산합니다.",
      "실패 한 번의 기억이 오래 남아 다음 선택을 더 작게 만듭니다.",
      "신중함은 강점이지만, 과하면 삶이 지나치게 방어적으로 바뀝니다.",
    ],
    pattern: "선택 앞에서 '얻을 것'보다 '잃지 않을 것'을 먼저 따지는 편입니다.",
    trigger: "과거 실패가 떠오르거나 손해 가능성이 수치로 보일 때 움직임이 크게 줄어듭니다.",
    weakness: "안전해 보이는 선택만 반복하다 보면 결국 가장 큰 손해는 놓친 기회가 됩니다.",
    advice: "모든 위험을 없애려 하지 말고 감당 가능한 손실 한도를 먼저 정해두는 방식이 더 좋습니다.",
  },
  belief: {
    id: "belief",
    emoji: "🧠",
    imagePath: "/assets/belief.png",
    name: "확신 중독자",
    hook: "한 번 믿으면 끝까지 갑니다. 틀렸어도 쉽게 바꾸지 않습니다",
    summary: "자기 판단에 대한 확신이 강해서 방향 전환이 어려운 타입입니다.",
    aura: "믿는 순간 밀어붙이는 강한 자기확신형",
    accent: "belief",
    keywords: ["확신", "고집", "직진"],
    detail: [
      "판단이 한번 굳어지면 반대 정보가 들어와도 잘 안 흔들립니다.",
      "추진력은 강하지만, 틀렸을 때 수정 비용이 커질 수 있습니다.",
      "자신감이 장점이지만 고집으로 읽히는 순간 신뢰를 깎을 수 있습니다.",
    ],
    pattern: "선택 후에는 근거를 더 모으기보다 내 판단이 맞다는 쪽으로 정렬되기 쉽습니다.",
    trigger: "내 권위나 판단이 흔들리는 장면에서 방어적으로 더 세게 버티게 됩니다.",
    weakness: "바꾸는 걸 패배처럼 느끼면, 틀린 선택을 오래 끌고 가게 됩니다.",
    advice: "입장을 바꾸는 걸 패배가 아니라 업데이트로 정의하면 훨씬 강한 사람이 됩니다.",
  },
  luck: {
    id: "luck",
    emoji: "🎲",
    imagePath: "/assets/luck.png",
    name: "운 과신형",
    hook: "이번엔 다를 거야. 이 생각으로 계속 선택합니다",
    summary: "패턴보다 운과 흐름에 기대며 다시 베팅하는 타입입니다.",
    aura: "합리화와 낙관으로 다시 뛰어드는 감각추종형",
    accent: "luck",
    keywords: ["낙관", "감", "재시도"],
    detail: [
      "이전 실패를 구조보다 타이밍 문제로 해석하는 경향이 있습니다.",
      "가볍게 회복하는 힘은 있지만 반복 실수를 부를 수 있습니다.",
      "분위기와 직감을 잘 타지만 기준이 없으면 흔들림도 큽니다.",
    ],
    pattern: "실패 후에도 '이번엔 다를 수 있다'는 기대감으로 다시 들어가는 편입니다.",
    trigger: "흐름이 좋아 보이거나 감이 온다고 느끼는 순간 판단 기준이 빠르게 느슨해집니다.",
    weakness: "원인 분석 없이 낙관으로 덮어버리면 같은 실수를 다른 이름으로 반복합니다.",
    advice: "감이 좋아도 최소한 하나의 객관 기준은 붙여야 반복 루프를 끊을 수 있습니다.",
  },
};

export const selfWorthProfiles: Record<string, CharacterProfile> = {
  mask: {
    id: "mask",
    emoji: "🎭",
    imagePath: "/assets/mask.png",
    name: "가면 연기자",
    hook: "겉으로는 괜찮아 보이지만 속은 다릅니다",
    summary: "남에게 보이는 모습과 실제 상태의 간격이 큰 타입입니다.",
    aura: "괜찮은 척 웃지만 속으로는 계속 흔들리는 이미지 관리형",
    accent: "mask",
    keywords: ["비교", "이미지", "숨김"],
    detail: [
      "실패나 약점을 들키는 걸 유난히 두려워하는 편입니다.",
      "겉으로 멀쩡해 보일수록 내면은 더 지칠 수 있습니다.",
      "칭찬에 기분이 좌우되고, 비교에 쉽게 흔들릴 가능성이 큽니다.",
    ],
    pattern: "괜찮아 보이는 모습은 유지하지만 실제 감정은 혼자서 감추는 경우가 많습니다.",
    trigger: "비교, 평가, 공개적인 실수 장면에서 자존감이 크게 흔들립니다.",
    weakness: "이미지 방어에 힘을 너무 쓰면 정작 자기 자신과 멀어질 수 있습니다.",
    advice: "완벽한 모습보다 솔직한 한 조각을 드러내는 연습이 내면 안정에 훨씬 도움이 됩니다.",
  },
  wall: {
    id: "wall",
    emoji: "🧱",
    imagePath: "/assets/wall.png",
    name: "방어벽 구축자",
    hook: "상처받기 전에 막습니다. 그래서 아무도 못 들어옵니다",
    summary: "약점을 숨기고 방어하는 방식으로 자신을 지키는 타입입니다.",
    aura: "강해 보이지만 사실은 상처를 먼저 차단하는 방어형",
    accent: "wall",
    keywords: ["방어", "차단", "경계"],
    detail: [
      "상처받지 않기 위해 먼저 벽을 세우는 습관이 있습니다.",
      "도움이 필요해도 쉽게 말하지 못하고 혼자 버티려는 경향이 있습니다.",
      "겉으로는 단단해 보여도, 가까운 관계에서는 차갑게 보일 수 있습니다.",
    ],
    pattern: "누가 가까워지거나 내 약점을 건드리면 무심함이나 방어적인 태도로 튕겨냅니다.",
    trigger: "비판, 지적, 취약한 감정을 들켜야 하는 순간 벽이 빠르게 올라갑니다.",
    weakness: "스스로를 지키는 데는 능하지만 그 벽 때문에 진짜 위로도 잘 못 들어옵니다.",
    advice: "모든 문을 열 필요는 없지만, 한 사람에게만이라도 솔직한 통로를 만들어두는 게 중요합니다.",
  },
  rooted: {
    id: "rooted",
    emoji: "🌿",
    imagePath: "/assets/rooted.png",
    name: "중심 잡힌 사람",
    hook: "흔들리지만 무너지지 않습니다. 자신을 비교적 잘 이해합니다",
    summary: "완벽하진 않아도 자기 상태를 비교적 건강하게 다루는 타입입니다.",
    aura: "부드럽지만 쉽게 무너지지 않는 자기이해형",
    accent: "rooted",
    keywords: ["안정", "수용", "자기이해"],
    detail: [
      "비교나 실패에 흔들려도 회복 속도가 비교적 빠른 편입니다.",
      "자신의 약점을 부정하기보다 관리하려는 태도가 있습니다.",
      "내면이 안정적이라 주변 사람에게도 편안함을 줄 수 있습니다.",
    ],
    pattern: "실패해도 자존감 전체가 무너지기보다 경험 하나로 분리해서 보려는 편입니다.",
    trigger: "지속적인 비교 환경이나 반복된 무시가 이어지면 이 타입도 꽤 지칠 수 있습니다.",
    weakness: "안정적이라는 이유로 본인도 힘든 시기를 과소평가할 수 있습니다.",
    advice: "스스로를 잘 아는 만큼, 버티는 것만 하지 말고 도움을 요청하는 타이밍도 챙기면 더 강해집니다.",
  },
};

export const decisionProfiles: Record<string, CharacterProfile> = {
  flash: {
    id: "flash",
    emoji: "⚡",
    imagePath: "/assets/flash.png",
    name: "번개 선택가",
    hook: "빠르게 결정하고, 나중에 후회합니다",
    summary: "속도는 빠르지만 감정과 충동이 결정을 앞지르기 쉬운 타입입니다.",
    aura: "망설임 없이 누르지만 뒤늦게 복기하는 즉흥형",
    accent: "flash",
    keywords: ["속도", "충동", "후회"],
    detail: [
      "결정 속도는 장점이지만 검토가 짧아 후회 확률이 높습니다.",
      "기회를 잡는 힘은 강하지만, 리스크도 함께 크게 안습니다.",
      "답답한 상황을 못 견뎌 빨리 끝내려는 경향이 있습니다.",
    ],
    pattern: "생각보다 느낌이 앞서고, 결정 자체로 답답함을 해소하려는 편입니다.",
    trigger: "시간 압박, 감정 고조, 선택 피로가 커질수록 더 빠르게 눌러버립니다.",
    weakness: "결정을 끝내는 데 집중하다 보면 결정의 질이 자주 희생됩니다.",
    advice: "중요한 선택일수록 최소 10분 유예 규칙 같은 작은 브레이크를 두는 게 효과적입니다.",
  },
  delay: {
    id: "delay",
    emoji: "🧊",
    imagePath: "/assets/delay.png",
    name: "무한 보류자",
    hook: "결정하지 않습니다. 그래서 아무것도 변하지 않습니다",
    summary: "실수보다 책임이 무서워 선택 자체를 미루는 타입입니다.",
    aura: "움직이지 않아서 안전을 확보하려는 정지형",
    accent: "delay",
    keywords: ["미룸", "불안", "정체"],
    detail: [
      "결정을 미루는 동안 불안은 줄지 않고 오히려 커질 수 있습니다.",
      "실패는 피하지만 기회와 변화도 함께 놓칠 가능성이 큽니다.",
      "완벽한 답을 기다리느라 시작조차 못 할 수 있습니다.",
    ],
    pattern: "정보를 더 모아야 할 것 같고 타이밍을 더 봐야 할 것 같아서 계속 멈춥니다.",
    trigger: "책임이 큰 선택, 실패 비용이 커 보이는 상황에서 특히 오래 얼어붙습니다.",
    weakness: "결정하지 않는 것도 결정인데, 그 사실을 잊는 순간 삶이 제자리에서 굳어버립니다.",
    advice: "완벽한 답 대신 '지금 가능한 최선'을 정하는 훈련이 보류 루프를 끊는 데 필요합니다.",
  },
  strategist: {
    id: "strategist",
    emoji: "🧭",
    imagePath: "/assets/strategist.png",
    name: "계산된 전략가",
    hook: "신중하게 판단합니다. 대신 기회를 놓칠 때도 있습니다",
    summary: "판단의 질은 높지만 속도전에서는 뒤처질 수 있는 타입입니다.",
    aura: "감정보다 구조를 먼저 보는 분석형",
    accent: "strategist",
    keywords: ["분석", "신중", "기회비용"],
    detail: [
      "감정에 휘둘리기보다 정보를 모으고 구조를 파악하려 합니다.",
      "결정 품질은 좋은 편이지만, 속도가 필요한 장면은 불리할 수 있습니다.",
      "잘 고르지만 타이밍을 놓친 뒤 뒤늦게 아쉬움을 느낄 수 있습니다.",
    ],
    pattern: "선택 전에 조건을 정리하고 비교하며 나름의 기준표를 세우는 편입니다.",
    trigger: "정보가 부족하거나 변수가 많을수록 더 오래 분석 모드에 머무르게 됩니다.",
    weakness: "맞는 선택을 고르려다 실행 타이밍을 놓치면 결국 좋은 선택도 의미가 줄어듭니다.",
    advice: "분석 종료 시점을 미리 정해두면 신중함은 지키면서도 실행력을 잃지 않을 수 있습니다.",
  },
};
